name: First Action
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print Multiline
        run: |
          echo "1st Line!"
          echo "2nd Line!"
      - name: Print GoodBye
        run: echo "Done - Bye!"
